"""Name constant description"""


class NameConstantDesc:
    """Name constant description"""

    NAME = {
        None: "nil",
        True: "true",
        False: "false",
    }


#### CONSTANTS ####
VERSION = "3.27.111"
TAB = "\t\b\b\b\b"

"""Header"""
HEADER = f"--> generated by roblox-py v{VERSION}\n"
PY_HEADER = f"## generated by roblox-py v{VERSION} ##\nfrom rbx import *\n"
